apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: git-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: git-dep
      eventSourceName: git-webhook-event
      eventName: git-webhook
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: git-checkout-test-
                namespace: argo
              spec:
                entrypoint: main
                templates:
                  - name: main
                    steps:
                      - - name: git-checkout
                          template: git-checkout
                      - - name: verify-work-directory
                          template: verify-work-directory

                  - name: git-checkout
                    container:
                      image: bitnami/git:latest
                      command: ["/bin/sh", "-c"]
                      args:
                        - |
                          mkdir -p /work
                          git clone https://github.com/regal2t/argo.git /work
                          cd /work && git checkout main
                          echo "Current Git SHA:"
                          git rev-parse HEAD > /work/git_sha.txt
                          ls /work
                      volumeMounts:
                        - name: work
                          mountPath: /work

                  - name: verify-work-directory
                    container:
                      image: alpine:latest
                      command: ["sh", "-c"]
                      args:
                        - |
                          echo "Contents of /work directory:"
                          ls -al /work
                          echo "Contents of /work/argo directory:"
                          ls -al /work/argo
                          echo "Git SHA:"
                          cat /work/git_sha.txt
                      volumeMounts:
                        - name: work
                          mountPath: /work

                volumes:
                  - name: work
                    emptyDir: {}