apiVersion: v1
kind: PersistentVolume
metadata:
  name: workdir-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"  # Ensure this directory exists on your node
