apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  source:
    repoURL: "https://github.com/regal2t/argo.git"
    path: "deployment"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
