apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-and-push-
  namespace: argo
spec:
  entrypoint: build
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Mi
  templates:
    - name: build
      steps:
        - - name: git-checkout
            template: git-checkout
        - - name: build-and-push
            template: build-and-push
        - - name: notify
            template: notify-slack

    - name: git-checkout
      container:
        image: bitnami/git:latest
        command: ["/bin/sh", "-c"]
        args: ["git clone https://github.com/regal2t/argo.git && cd argo && git checkout main"]
      volumeMounts:
        - name: work
          mountPath: /work

    - name: build-and-push
      container:
        image: docker:20.10.7
        command: ["sh", "-c"]
        args:
          - |
            cd /argo # This ensures you are in the right directory where the Dockerfile is located
            docker build -t rajutiwari2024/argo-test:latest .
            echo "Logging in to Docker Hub..."
            echo "Building Docker Image..."
            echo "Pushing Docker Image..."
            docker push rajutiwari2024/argo-test:latest
            echo "Docker Image pushed successfully!"
        volumeMounts:
          - name: work
            mountPath: /work
        imagePullSecrets:
          - name: dockerhub-secret

    - name: notify-slack
      container:
        image: curlimages/curl
        command: ["sh", "-c"]
        args: ["curl -X POST -H 'Content-type: application/json' --data '{\"text\": \"Build and Deployment Completed!\"}' $SLACK_WEBHOOK"]
        env:
          - name: SLACK_WEBHOOK
            value: "your-slack-webhook-url"
