apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-and-push-
  namespace: argo
spec:
  entrypoint: build
  templates:
    - name: build
      steps:
        - - name: git-checkout
            template: git-checkout
        - - name: build-and-push
            template: build-and-push
        - - name: notify
            template: notify-slack

    - name: git-checkout
      container:
        image: bitnami/git:latest
        command: ["/bin/sh", "-c"]
        args: ["git clone https://github.com/regal2t/argo.git && cd argo && git checkout main"]

    - name: build-and-push
      container:
        image: ghcr.io/containerd/containerd:v1.5.10
        command: ["sh", "-c"]
        args:
          - |
            echo "Logging in to Docker Hub..."
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            echo "Building Docker Image..."
            docker build -t rajutiwari2024/argo-test:latest .
            echo "Pushing Docker Image..."
            docker push rajutiwari2024/argo-test:latest
            echo "Docker Image pushed successfully!"
        env:
          - name: DOCKER_USERNAME
            valueFrom:
              secretKeyRef:
                name: dockerhub-secret
                key: username
          - name: DOCKER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dockerhub-secret
                key: password

    - name: notify-slack
      container:
        image: curlimages/curl
        command: ["sh", "-c"]
        args: ["curl -X POST -H 'Content-type: application/json' --data '{\"text\": \"Build and Deployment Completed!\"}' $SLACK_WEBHOOK"]
        env:
          - name: SLACK_WEBHOOK
            value: "your-slack-webhook-url"
