apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp-rollout
  namespace: myapp
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 30s
  selector:
    matchLabels:
      app: myapp  # This label will match the Pods created by this Rollout
  template:
    metadata:
      labels:
        app: myapp  # Ensure this label matches the selector above
    spec:
      containers:
        - name: myapp
          image: rajutiwari2024/argo-test:f6346d9
          ports:
            - containerPort: 80
              protocol: TCP
