apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp-rollout
  namespace: myapp
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: 10m}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myrepo/app:latest
          ports:
            - containerPort: 80
